"""The hook against the golden wire contracts in ``contracts/`` (no kb_service import).

``contracts/*.json`` are generated by ``packages/kb-service/scripts/gen_contracts.py``
from the server's models; these tests prove the hook still speaks that contract.
"""

from __future__ import annotations

import json
import urllib.parse
import urllib.request
from pathlib import Path
from typing import Any

import pytest
from jsonschema import Draft202012Validator

from personal_kb_hook import paths, prevention, turn_digest, turn_sender

HOOK_ITEM_KINDS = frozenset({"assistant_text", "tool_call", "tool_result"})
HOOK_OMITTED_REQUEST_FIELDS: frozenset[str] = frozenset()
HOOK_OMITTED_ITEM_FIELDS: dict[str, frozenset[str]] = {}
EXPECTED_SENDER_RESULT: dict[str, str | None] = {
    "recorded": None,
    "duplicate": None,
    "capture-off": None,
    "duplicate-mismatch": "rejected_duplicate-mismatch",
    "redaction-unavailable": "rejected_redaction-unavailable",
    "write-failed": "rejected_write-failed",
}

_CONTRACTS = Path(__file__).resolve().parents[3] / "contracts"
_SID = "contract-session-1"


def _load(name: str) -> dict[str, Any]:
    doc = json.loads((_CONTRACTS / f"{name}.json").read_text(encoding="utf-8"))
    assert isinstance(doc, dict)
    return doc


PREVENTION = _load("prevention")
TURN = _load("turn")
RESPONSE_EXAMPLES = PREVENTION["response"]["examples"]
TURN_RESPONSE_EXAMPLES = TURN["response"]["examples"]


class _Resp:
    def __init__(self, status: int = 200, body: bytes = b"{}") -> None:
        self.status = status
        self._body = body

    def getcode(self) -> int:
        return self.status

    def read(self) -> bytes:
        return self._body

    def __enter__(self) -> _Resp:
        return self

    def __exit__(self, *args: object) -> None:
        return None


class _Server:
    """Fake urlopen: records every Request and answers with ``body``."""

    def __init__(self) -> None:
        self.requests: list[Any] = []
        self.body: bytes = b"{}"

    def __call__(self, req: Any, timeout: float = 30.0) -> _Resp:
        self.requests.append(req)
        return _Resp(200, self.body)


@pytest.fixture(autouse=True)
def _env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("PERSONAL_KB_URL", "https://kb.example.test")
    monkeypatch.setenv("PERSONAL_KB_API_KEY", "test-key")
    monkeypatch.setenv("HOME", str(tmp_path / "home"))
    monkeypatch.setenv("XDG_CONFIG_HOME", str(tmp_path / ".config"))
    monkeypatch.setenv("KB_DB_PATH", str(tmp_path / "kb" / "knowledge.db"))
    for var in (
        "HEADLESS_BUILD_ENGINE",
        "PERSONAL_KB_LISTENER",
        "KB_INSTANCE_ROLE",
        "KB_GOTCHA_SLICE",
    ):
        monkeypatch.delenv(var, raising=False)
    (tmp_path / "home" / ".cache" / "personal_kb").mkdir(parents=True)


@pytest.fixture
def server(monkeypatch: pytest.MonkeyPatch) -> _Server:
    srv = _Server()
    monkeypatch.setattr(urllib.request, "urlopen", srv)
    return srv


def _start_payload(tmp_path: Path) -> dict[str, Any]:
    repo = tmp_path / "git" / "personal_kb"
    repo.mkdir(parents=True)
    (repo / ".kb_project").write_text("personal-kb\n", encoding="utf-8")
    return {
        "hook_event_name": "SessionStart",
        "session_id": _SID,
        "cwd": str(repo),
        "source": "startup",
    }


def _body(name: str) -> dict[str, Any]:
    return next(e["body"] for e in RESPONSE_EXAMPLES if e["name"] == name)


def _pre(command: str, tool_use_id: str) -> dict[str, Any]:
    return {
        "hook_event_name": "PreToolUse",
        "session_id": _SID,
        "tool_name": "Bash",
        "tool_use_id": tool_use_id,
        "tool_input": {"command": command},
    }


def _cache() -> dict[str, Any]:
    return json.loads(paths.get_prevention_cache_path(_SID).read_text())


def _reason(raw: str | None) -> str:
    assert raw is not None
    out = json.loads(raw)["hookSpecificOutput"]
    assert out["permissionDecision"] == "deny"
    return str(out["permissionDecisionReason"])


# --- prevention: request ------------------------------------------------------


def test_prevention_request_matches_fixture(tmp_path: Path, server: _Server) -> None:
    server.body = json.dumps(_body("gate_armed")).encode()
    prevention.session_start(_start_payload(tmp_path))
    assert len(server.requests) == 1
    req = server.requests[0]
    split = urllib.parse.urlsplit(req.full_url)
    assert req.get_method() == PREVENTION["method"]
    assert split.path == PREVENTION["path"]
    assert req.get_header("Authorization") == "Bearer test-key"
    query = dict(urllib.parse.parse_qsl(split.query, keep_blank_values=True))
    schema = PREVENTION["request"]["query_schema"]
    assert Draft202012Validator(schema).is_valid(query)
    assert set(query) >= set(schema["required"])
    assert query["project"] == "personal-kb"


# --- prevention: responses ----------------------------------------------------


@pytest.mark.parametrize("example", RESPONSE_EXAMPLES, ids=[e["name"] for e in RESPONSE_EXAMPLES])
def test_prevention_response_example_is_consumed(
    example: dict[str, Any], tmp_path: Path, server: _Server
) -> None:
    body = example["body"]
    server.body = json.dumps(body).encode()
    text = prevention.session_start(_start_payload(tmp_path))
    assert text == (body["slice_text"] or None)
    cache = _cache()
    assert cache["project"] == body["project"]
    assert cache["index"] == body["index"]
    assert cache["surprise_capture"] == body["surprise_capture"]
    keys = ("enabled", "shadow", "max_denies_per_turn", "max_denies_per_hour", "rearm_hours")
    assert cache["gate"] == {k: body["gate"][k] for k in keys}


def test_armed_gate_denies_matching_calls(tmp_path: Path, server: _Server) -> None:
    body = _body("gate_armed")
    server.body = json.dumps(body).encode()
    prevention.session_start(_start_payload(tmp_path))
    first = prevention.pre_tool(_pre("git push mirror main", "toolu_a"))
    assert _reason(first) == prevention.build_reason(body["index"][0])
    prevention.new_turn({"session_id": _SID})
    assert prevention.pre_tool(_pre("git remote -v", "toolu_b")) is None
    second = prevention.pre_tool(_pre("git remote add upstream git@example.com:r.git", "toolu_c"))
    assert _reason(second) == prevention.build_reason(body["index"][1])


def test_disabled_gate_never_denies(tmp_path: Path, server: _Server) -> None:
    armed = _body("gate_armed")
    disabled = {**armed, "gate": {**armed["gate"], "enabled": False}}
    server.body = json.dumps(disabled).encode()
    prevention.session_start(_start_payload(tmp_path))
    assert _cache()["gate"]["enabled"] is False
    assert prevention.pre_tool(_pre("git push mirror main", "toolu_a")) is None


def test_prevention_constants_match_fixture() -> None:
    schema = PREVENTION["response"]["schema"]
    modes = schema["properties"]["surprise_capture"]["enum"]
    assert set(prevention.SURPRISE_CAPTURE_MODES) == set(modes)
    props = schema["$defs"]["GateSettings"]["properties"]
    assert props["max_denies_per_turn"]["default"] == prevention.DEFAULT_MAX_DENIES_PER_TURN
    assert props["max_denies_per_hour"]["default"] == prevention.DEFAULT_MAX_DENIES_PER_HOUR
    assert props["rearm_hours"]["default"] == prevention.DEFAULT_REARM_HOURS


# --- turn: request ------------------------------------------------------------


def _write(path: Path, records: list[dict[str, Any]]) -> str:
    path.write_text("\n".join(json.dumps(r) for r in records) + "\n", encoding="utf-8")
    return str(path)


def _prompt(text: str) -> dict[str, Any]:
    return {"type": "user", "uuid": "p", "origin": {"kind": "human"}, "message": {"content": text}}


def _use(i: int, cmd: str) -> dict[str, Any]:
    block = {"type": "tool_use", "id": f"t{i}", "name": "Bash", "input": {"command": cmd}}
    return {"type": "assistant", "uuid": f"a{i}", "message": {"content": [block]}}


def _result(i: int, text: str, is_error: bool = True) -> dict[str, Any]:
    block = {"type": "tool_result", "tool_use_id": f"t{i}", "content": text, "is_error": is_error}
    return {"type": "user", "uuid": f"r{i}", "message": {"content": [block]}}


def _text(text: str) -> dict[str, Any]:
    block = {"type": "text", "text": text}
    return {"type": "assistant", "uuid": "x", "message": {"content": [block]}}


def _thinking() -> dict[str, Any]:
    block = {"type": "thinking", "thinking": "plan"}
    return {"type": "assistant", "uuid": "th", "message": {"content": [block]}}


def _digest(path: Path, records: list[dict[str, Any]]) -> bytes:
    window = turn_digest.read_turn(_write(path, records), None)
    raw = turn_digest.build_digest(
        {"session_id": "s1", "last_assistant_message": "done"},
        turn_index=3,
        project="personal-kb",
        window=window,
    )
    assert raw is not None
    return raw


def _max_length(prop: dict[str, Any]) -> int:
    if "maxLength" in prop:
        return int(prop["maxLength"])
    return next(int(m["maxLength"]) for m in prop["anyOf"] if m.get("type") == "string")


def test_turn_request_matches_fixture(tmp_path: Path) -> None:
    schema = TURN["request"]["schema"]
    mapping = schema["properties"]["items"]["items"]["discriminator"]["mapping"]
    raw = _digest(
        tmp_path / "t.jsonl",
        [
            _prompt("go"),
            _thinking(),
            _text("hi"),
            _use(1, "git push mirror main"),
            _result(1, "denied"),
        ],
    )
    body = json.loads(raw)
    assert Draft202012Validator(schema).is_valid(body)
    assert len(raw) <= TURN["request"]["max_body_bytes"]
    missing = (set(schema["properties"]) - HOOK_OMITTED_REQUEST_FIELDS) - set(body)
    assert not missing, (
        f"request field(s) {sorted(missing)} not sent by the hook; send them in "
        "turn_digest.build_digest or list them in HOOK_OMITTED_REQUEST_FIELDS"
    )
    assert set(body) == set(schema["properties"]) - HOOK_OMITTED_REQUEST_FIELDS
    assert set(schema.get("required", [])) <= set(body)
    assert body["event_id"] == f"{body['session_id']}:{body['turn_index']}"
    for item in body["items"]:
        ref = mapping[item["kind"]].removeprefix("#/$defs/")
        want = set(schema["$defs"][ref]["properties"])
        assert set(item) == want - HOOK_OMITTED_ITEM_FIELDS.get(item["kind"], frozenset())
    assert {i["kind"] for i in body["items"]} == HOOK_ITEM_KINDS
    assert set(mapping) >= HOOK_ITEM_KINDS


def test_turn_truncation_stays_within_limit(tmp_path: Path) -> None:
    records = [_prompt("go")]
    for i in range(60):
        records += [_use(i, f"ls {i}"), _result(i, "r" * 3000)]
    raw = _digest(tmp_path / "t.jsonl", records)
    body = json.loads(raw)
    assert Draft202012Validator(TURN["request"]["schema"]).is_valid(body)
    assert body["truncated"] is True
    assert len(raw) <= TURN["request"]["max_body_bytes"]


def test_turn_caps_match_fixture() -> None:
    schema = TURN["request"]["schema"]
    props = schema["properties"]
    defs = schema["$defs"]
    assert TURN["request"]["max_body_bytes"] == turn_digest.TURN_DIGEST_MAX_BYTES
    assert props["items"]["maxItems"] == turn_digest.TURN_ITEMS_MAX
    assert _max_length(props["user_prompt"]) == turn_digest.TURN_USER_PROMPT_MAX
    assert _max_length(props["final_message"]) == turn_digest.TURN_FINAL_MESSAGE_MAX
    assert (
        defs["TurnAssistantTextItem"]["properties"]["text"]["maxLength"]
        == turn_digest.TURN_TEXT_MAX
    )
    assert (
        defs["TurnToolCallItem"]["properties"]["target"]["maxLength"] == turn_digest.TURN_TARGET_MAX
    )
    assert (
        defs["TurnToolResultItem"]["properties"]["excerpt"]["maxLength"]
        == turn_digest.TURN_EXCERPT_MAX
    )
    modes = PREVENTION["response"]["schema"]["properties"]["surprise_capture"]["enum"]
    assert set(modes) >= turn_digest.SEND_MODES


# --- turn: responses and sender -----------------------------------------------


def test_sender_classifies_every_server_reason() -> None:
    reasons = set(TURN["response"]["schema"]["properties"]["reason"]["enum"])
    unclassified = sorted(reasons - set(EXPECTED_SENDER_RESULT))
    stale = sorted(set(EXPECTED_SENDER_RESULT) - reasons)
    assert not unclassified and not stale, (
        f"unclassified reason(s) {unclassified}, stale {stale}: classify each in "
        "turn_sender.REJECT_REASONS and in EXPECTED_SENDER_RESULT"
    )
    rejected = {r for r, v in EXPECTED_SENDER_RESULT.items() if v is not None}
    assert set(turn_sender.REJECT_REASONS) == rejected


@pytest.mark.parametrize(
    "example", TURN_RESPONSE_EXAMPLES, ids=[e["name"] for e in TURN_RESPONSE_EXAMPLES]
)
def test_sender_handles_response_example(
    example: dict[str, Any], tmp_path: Path, server: _Server
) -> None:
    request = next(
        e["body"] for e in TURN["request"]["examples"] if e["name"] == "claude_code_turn"
    )
    path = tmp_path / f"body-{example['name']}.json"
    path.write_text(json.dumps(request), encoding="utf-8")
    server.body = json.dumps(example["body"]).encode()
    result = turn_sender.send_file(str(path), "s1")
    assert result == EXPECTED_SENDER_RESULT[example["name"]]
    assert not path.exists()
    (req,) = server.requests
    assert req.get_method() == "POST"
    assert urllib.parse.urlsplit(req.full_url).path == TURN["path"]
    assert req.get_header("Content-type") == "application/json"
    rows = [
        json.loads(line) for line in paths.get_turn_digest_log_path("s1").read_text().splitlines()
    ]
    assert rows[-1]["server_reason"] == example["body"]["reason"]
    assert rows[-1]["redactions"] == len(example["body"]["redactions"])
